# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(('Mr',), 'Mr'), (('Mrs',), 'Mrs'), (('Ms',), 'Ms'), ('Sir', 'Sir')], max_length=120, null=True)),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('second_name', models.CharField(max_length=120, null=True)),
                ('third_name', models.CharField(blank=True, max_length=120, null=True)),
                ('depertment', models.CharField(choices=[(('CSE',), 'CSE'), (('ECE',), 'ECE'), (('MECH',), 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True)),
                ('subjects', models.CharField(max_length=120, null=True)),
                ('date_registered', models.DateField(max_length=120, null=True)),
                ('time_arrived', models.DateTimeField(max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
