# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='depertment',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Sir', 'Sir')], max_length=120, null=True),
        ),
    ]
