# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_auto_20180104_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='date_registered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
