# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0009_auto_20180104_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
