# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0010_auto_20180104_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('image', models.FileField(null=True, upload_to='')),
                ('comments', models.CharField(max_length=120, null=True)),
                ('likes', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
