# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attend', '0014_auto_20180211_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Sir', 'Sir')], max_length=120, null=True)),
                ('first_name', models.CharField(max_length=120, null=True)),
                ('second_name', models.CharField(max_length=120, null=True)),
                ('third_name', models.CharField(blank=True, max_length=120, null=True)),
                ('depertment', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True)),
                ('subjects', models.CharField(max_length=120, null=True)),
                ('finger_print', models.CharField(max_length=300)),
                ('date_registered', models.DateField(auto_now_add=True, null=True)),
                ('phone_number', models.CharField(max_length=120, null=True)),
                ('position_type', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
