# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0017_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
