# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0020_realsignout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsdates',
            name='Day',
        ),
        migrations.RemoveField(
            model_name='eventsdates',
            name='Month',
        ),
        migrations.RemoveField(
            model_name='eventsdates',
            name='year',
        ),
        migrations.AddField(
            model_name='eventsdates',
            name='Date',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
