# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0023_uploadnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadnotes',
            name='FileNotes',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
