# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0024_auto_20180605_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadnotes',
            name='Field',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
