# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-05 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0025_auto_20180605_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='Field',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='FileNotes',
            new_name='filenotes',
        ),
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='Semister',
            new_name='semister',
        ),
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='uploadnotes',
            old_name='Year',
            new_name='year',
        ),
    ]
