# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0026_auto_20180605_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadnotes',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
