# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0027_uploadnotes_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
