# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0028_smsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadnotes',
            name='field',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='uploadnotes',
            name='filenotes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadnotes',
            name='semister',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='uploadnotes',
            name='subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='uploadnotes',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='uploadnotes',
            name='year',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
