# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0029_auto_20180610_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realatendance',
            name='finger_print',
        ),
    ]
