# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0030_remove_realatendance_finger_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='realatendance',
            name='finger_print',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
