# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0031_realatendance_finger_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realatendance',
            name='depertment',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ISNE', 'ISNE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='realsignout',
            name='depertment',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ISNE', 'ISNE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='depertment',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ISNE', 'ISNE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='depertment',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ISNE', 'ISNE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EDUCATION', 'EDUCATION')], max_length=120, null=True),
        ),
    ]
